// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6csoKc-OuuNQDuiz8j272d7pSPzJfSk',
    appId: '1:855956647821:web:8f90350ebd6fbb17dc97c4',
    messagingSenderId: '855956647821',
    projectId: 'coffee-billboard-app',
    authDomain: 'coffee-billboard-app.firebaseapp.com',
    databaseURL: 'https://coffee-billboard-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-billboard-app.firebasestorage.app',
    measurementId: 'G-RYG6CVE5R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZLJ-91cTXqm_w1d8UUJXrIaMNaEi1Ng',
    appId: '1:855956647821:android:01f87859f5dbf7b9dc97c4',
    messagingSenderId: '855956647821',
    projectId: 'coffee-billboard-app',
    databaseURL: 'https://coffee-billboard-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-billboard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsTwloAQHS2JS03AQ5stPdfMt48HCb0xM',
    appId: '1:855956647821:ios:92e9e884491ea3f7dc97c4',
    messagingSenderId: '855956647821',
    projectId: 'coffee-billboard-app',
    databaseURL: 'https://coffee-billboard-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-billboard-app.firebasestorage.app',
    iosBundleId: 'com.example.myCoffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsTwloAQHS2JS03AQ5stPdfMt48HCb0xM',
    appId: '1:855956647821:ios:92e9e884491ea3f7dc97c4',
    messagingSenderId: '855956647821',
    projectId: 'coffee-billboard-app',
    databaseURL: 'https://coffee-billboard-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-billboard-app.firebasestorage.app',
    iosBundleId: 'com.example.myCoffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo6csoKc-OuuNQDuiz8j272d7pSPzJfSk',
    appId: '1:855956647821:web:9c80fed34cf8a1c6dc97c4',
    messagingSenderId: '855956647821',
    projectId: 'coffee-billboard-app',
    authDomain: 'coffee-billboard-app.firebaseapp.com',
    databaseURL: 'https://coffee-billboard-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coffee-billboard-app.firebasestorage.app',
    measurementId: 'G-NW9FY7400H',
  );
}
